:toc:

== Определения

[quote, https://vk.com/just_wiki]
____
ГМО - генное оружие, успешно использующееся для сокращения численности населения Земли с четырёх до семи миллиардов человек
____

ГМО - https://ru.wikipedia.org/wiki/%D0%93%D0%B5%D0%BD%D0%B5%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8_%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D1%86%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BE%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%BC[генетически модифицированный организм]. Для того, чтобы было понятно, что это за монстр, нужно уточнить, что такое гены. В минимальном виде цепочка понятий выглядит так:
https://ru.wikipedia.org/wiki/%D0%9E%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%BC[Организмы] состоят из
https://ru.wikipedia.org/wiki/%D0%9A%D0%BB%D0%B5%D1%82%D0%BA%D0%B0[клеток], в клетках есть
https://ru.wikipedia.org/wiki/%D0%9A%D0%BB%D0%B5%D1%82%D0%BE%D1%87%D0%BD%D0%BE%D0%B5_%D1%8F%D0%B4%D1%80%D0%BE[ядро], в ядре есть
https://ru.wikipedia.org/wiki/%D0%A5%D1%80%D0%BE%D0%BC%D0%BE%D1%81%D0%BE%D0%BC%D0%B0[хромосомы], каждая хромосома это молекула
https://ru.wikipedia.org/wiki/%D0%94%D0%B5%D0%B7%D0%BE%D0%BA%D1%81%D0%B8%D1%80%D0%B8%D0%B1%D0%BE%D0%BD%D1%83%D0%BA%D0%BB%D0%B5%D0%B8%D0%BD%D0%BE%D0%B2%D0%B0%D1%8F_%D0%BA%D0%B8%D1%81%D0%BB%D0%BE%D1%82%D0%B0[ДНК] (не у всех организмов устройство соответствует описанному, но для целей данной статьи это достаточно точная формулировка). ДНК — это длинная молекула, состоящая из
https://ru.wikipedia.org/wiki/%D0%9D%D1%83%D0%BA%D0%BB%D0%B5%D0%BE%D1%82%D0%B8%D0%B4%D1%8B[нуклеотидов]. Участок ДНК, состоящий из множества нуклеотидов, и кодирующий синтез одного белка и называется https://ru.wikipedia.org/wiki/%D0%93%D0%B5%D0%BD[геном] (ген может влиять как на один признак организма, например, цвет глаз. как и на несколько признаков). Набор ДНК из всех хромосом клетки и есть основной носитель наследственной информации.
Чаще всего при генетической модификации изменение касается одного гена, отвечающего за тот признак организма, который нужно изменить. Во многих случаях ген с необходимыми функциями берётся из того организма, который обладает желаемой характеристикой (тогда такой ген называется https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B0%D0%BD%D1%81%D0%B3%D0%B5%D0%BD[трансгеном]).

== Концепция

Эволюция не делает совершенства, она делает рабочие решения. Например, http://geektimes.ru/post/248678/[зелёные растения умеют поглощать далеко не весь спектр солнечного излучения], и, возможно, мы когда-то сможем улучшить растения, повысив их эффективность - они будут расти быстрее при той же освещённости.
Также и с едой для человека - в природе нет такого продукта, который содержал бы всё необходимое для его питания, в результате эволюции такого не появилось (точнее мы не приспособились питаться чем-то одним) т.к. наши всеядные предки, до освоения земледелия и скотоводства, вынуждены были употреблять разнообразную пищу (что нашёл, то и съел).
С практической точки зрения было бы значительно удобнее если бы все выращиваемые культуры содержали полный набор питательных веществ. Тогда количество этих культур определялось бы только задачами обеспечения устойчивости (нужно иметь несколько культур, чтобы один паразит или засуха не могли уничтожить всё сельское хозяйство, пример это история http://www.nkj.ru/archive/articles/5240/[бананов]) и вкусовыми предпочтениями. Например все фрукты станут универсальной едой и любитель яблок сможет съедать несколько яблок в день и получать всё необходимое для нормального функционирования его организма.
Конечно, любители изысканной кухни могут не обрадоваться такому варианту, но для них останутся и старые продукты, а значительная часть людей предпочтёт тратить на еду и её приготовление меньше времени и денег, получая при этом максимально полезную пищу без сложных диет.

Таким образом, генетическая модификация, которую делают сегодня, это лишь первые шаги в большом пути по обеспечению человечества качественным и удобным питанием.

И, вполне возможно, что дерево, на котором будет расти такой универсальный питательный фрукт, будет нашим домом - оно будет вырастать с комнатами, пригодными для проживания человека - живой, саморемонтирующийся дом.

=== Текущие цели модификации

Текущие цели генной модификации часто далеки от вышеописанной концепции (http://elementy.ru/news?discuss=431862&return=1[даже вкус менее важен чем внешний вид]), хотя есть и примеры, идущие правильным путём (например https://ru.wikipedia.org/wiki/%D0%97%D0%BE%D0%BB%D0%BE%D1%82%D0%BE%D0%B9_%D1%80%D0%B8%D1%81[рис, богатый витамином А] или http://naked-science.ru/article/sci/bagrovye-pomidory-gmo-vskore-p[противораковые помидоры]):

. устойчивость к пестицидам - заливают пестицидами, гибнет всё кроме нужного растения. Не самый позитивный вариант, но не ГМО тоже заливают пестицидами, просто по более сложным схемам.
. устойчивость к загрязнителям почвы - для выращивания, например, на засоленных почвах, где почти ничего не растёт.
. устойчивость к вредителям - что может быть радостнее для сельхозпроизводителя, чем картошка без колорадского жука?
. повышение урожайности - плоды крупнее и число их больше.
. устойчивость к колебаниям погоды, морозостойкость.
. получение каких-либо сложнополучаемых веществ, в основном лекарственных, например инсулина.
. повышение полезности - пока редко (как вышеупомянутые витаминизированный рис и противораковые помидоры), но настанет и для этого время.
. наделение организмов дополнительными функциями, например, научить бактерии перерабатывать отходы или не допускать развития кариеса.

То, что текущие цели модификации редко связаны с полезностью продуктов не должно удивлять - сельское хозяйство рискованный бизнес (климат и паразиты губят растения) и первоочередная задача повысить стабильность урожая, после её решения компании-поставщики ГМО сортов возьмутся за повышение полезности.

== Страшилки и мифы

[quote, А.С. Пушкин о строительстве железных дорог в России]
____
Каковы же были аргументы противников строительства в России железных дорог? Наряду с известными нелепостями, извлекаемыми, как водится, из европейской прессы (железные дороги помешают коровам пастись, куры перестанут нести яйца, отравленный дымом воздух будет убивать пролетающих птиц, быстрота движе­ния будет развивать у путешественника болезнь мозга и т. д.), были и более серьезные аргументы.
____

К сожалению, множество людей позволяет себе рассуждать о том, о чем не имеют ни малейшего понятия, например согласно опросам, около половины респондентов считает, что гены есть только в ГМО, что говорит об отсутствии каких-либо знаний в этом вопросе.
А всё новое и неизвестное вызывает опасения, когда-то боялись, что от шума паровозов коровы перестанут пастись, куры - нестись, а кролики - размножаться, теперь боятся https://ru.wikipedia.org/wiki/%D0%91%D0%BE%D0%BB%D1%8C%D1%88%D0%BE%D0%B9_%D0%B0%D0%B4%D1%80%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BA%D0%BE%D0%BB%D0%BB%D0%B0%D0%B9%D0%B4%D0%B5%D1%80[коллайдера] и ГМО. Некоторые люди даже проявляли агрессию - были случаи нападений на научные лаборатории.
Всё кажущееся опасным люди любят запрещать, хотя это редко приводит к положительным результатам, и редко сторонники жёстких ограничений бывают последовательными - автомобили и водка доказано опасны, хотя что-то никто не спешит от их отказываться.

=== Превращение потомков людей в мутантов

*Генетическая модификация по своему результату принципиально (качественно) не отличается от https://ru.wikipedia.org/wiki/%D1%E5%EB%E5%EA%F6%E8%FF[селекции]*, только при селекции селекционер долго ждет появления нужной ему https://ru.wikipedia.org/wiki/%D0%9C%D1%83%D1%82%D0%B0%D1%86%D0%B8%D1%8F[мутации], а генетический инженер сам вносит нужное изменение в ДНК. Поэтому опасность ГМО не отличается от опасности новых сортов, полученных старыми мичуринскими методами, точнее она даже ниже, т.к. даже случайные мутации могут затрагивать множество генов помимо желаемого, а значит *при селекции непредсказуемость последствий выше, чем при целенаправленном изменении конкретного гена*.
А раз принципиальной разницы нет, то и нет никакого магического действия - мы едим помидоры и селёдку, однако это не делает наших потомков похожими на кого-то из съеденных. *В нашем желудке под действием https://ru.wikipedia.org/wiki/%D0%96%D0%B5%D0%BB%D1%83%D0%B4%D0%BE%D1%87%D0%BD%D1%8B%D0%B9_%D1%81%D0%BE%D0%BA[соляной кислоты и ферментов] большая часть молекул ДНК разваливаются на отдельные нуклеотиды т.е. перестают быть генами. и все http://progenes.livejournal.com/61431.html[исследования] показывают что они никогда не встраиваются в ДНК съевшего их*, что логично т.к. https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%BF%D0%B0%D1%80%D0%B0%D1%86%D0%B8%D1%8F_%D0%94%D0%9D%D0%9A[ДНК защищена от поломок]. Опять же, тут ничего о ГМО, мы всегда ели еду содержащую ДНК других организмов, если бы это меняло нашу ДНК, мы скорее всего давно стали бы похожими на пшеницу.
Поедание помидора с геном селедки скорее всего не отличается от поедания селёдки с помидором. Однако любой новый сорт (выведенный селекционерами или созданный генными инженерами) может содержать токсины или аллергены, и, конечно, его необходимо всячески проверять перед выпуском на рынок. На удивление, ГМО проверяют строже, чем обычные гибриды, полученные, например, радиоактивным облучением семян.
Ещё важный момент - всё живое на Земле родственно, никакой проблемы в переносе генов нет (трансгенах), например:
[quote, http://evoldar.com/evo21.htm]
____
Ученые перенесли ген, контролирующий развитие глаза у мыши в геном дрозофилы. ... мышиный ген индуцировал у мухи развитие мушиных глаз.
____
[quote, http://elementy.ru/news/432487]
____
Несмотря на то что человека и дрожжи разделяет миллиард лет эволюции, у них есть сотни генов с общим происхождением и функциями. Оказывается, около половины таких генов человека всё еще способны заменить соответствующие гены дрожжей.
____
Т.е. *мы настолько близки, что даже некоторые гены дрожжей и человека, мухи и мыши взаимозаменяемы*.

=== Они же не проверены временем

На самом деле, есть исследования на многих поколениях подопытных животных, за десятки лет исследований было всего несколько негативных результатов, которые не подтвердились при более тщательной проверке.

Зато алкоголь проверен - он тщательно исследован и точно известно что он является https://ru.wikipedia.org/wiki/%D0%9C%D1%83%D1%82%D0%B0%D0%B3%D0%B5%D0%BD%D1%8B[мутагеным] фактором, т.е. может сделать потомков уродами, но что-то ГМО боятся больше, чем водки.

Ну и на самом деле *не ГМО продуктов нет*, все значимые культуры были селекционированы человеком ещё на заре сельского хозяйства, и они значительно отличаются от своих диких собратьев не только размерами, но и другими свойствами, т.е. они генетически отличаются от своих предков. Например, зерновые — это мутанты, которые, в отличие от диких предков, прорастают и дают урожай в первый год (в дикой природе многие семена прорастают через год и более для страховки от непогоды), а также не выбрасывают зёрна из колосьев, чтобы человек мог их собрать. Размеры также отличаются значительно, початок дикой кукурузы во много раз меньше культурной. Мало того, некоторые дикие предки культурных растений ядовиты - например у https://ru.wikipedia.org/wiki/%D0%9C%D0%B8%D0%BD%D0%B4%D0%B0%D0%BB%D1%8C[миндаля]. А что сделали селекционеры с помощью радиации и токсинов задолго до ГМО и не представить, т.е. мы *ели, едим и будем есть ГМО, без них человечество не прокормить*.

=== Аллергенность

Также не зависит от способа получения, основные аллергены существовали ещё до изобретения ГМО, поэтому любой новый продукт надо тестировать на содержание известных и неизвестных аллергенов.

=== Передача генов устойчивости к пестицидам диким растениям

Это возможно, хотя, согласно исследованиям, маловероятно, к тому же http://progenes.livejournal.com/196636.html[устойчивость вырабатывается сама без всяких ГМО], таково свойство жизни - эволюционировать приспосабливаясь к условиям, если среда наполнилась ядами, то скоро возникнут те, кто их не боится.

=== Раз жуки не едят — и нам нельзя

Тут ГМО тоже не отличается от сортов, полученных селекцией, - селекционер выбирает растения, не интересующие паразитов, по тем или иным причинам, в том числе — они могут быть ядовиты для паразитов, но это не значит, что и для человека они ядовиты - "что человеку хорошо, то жуку смерть". Например, есть белок-токсин, нарушающий пищеварение у насекомых, но не у теплокровных животных.
Безопасность для человека определяется исследованиями на животных, максимально близких к человеку, а сейчас активно развиваются технологии для тестирования на отдельно выращенных тканях человека, жуки тут не авторитеты.

== Селекция

Как уже говорилось, генетическая модификация делает то же самое, что и селекция, но быстрее и более предсказуемо. Несколько примеров того, как без ГМО можно натворить дел, а значит надо быть осторожными, но не запрещать, а контролировать.

[quote, "Миф о трансгенной угрозе", Наука и жизнь]
____
Примером появления непредсказуемых эффектов в обычной селекции служит история с гибридом кукурузы "Техас". В начале 70-х огромные посевные площади этой культуры в США были опустошены грибковым заболеванием. Выяснилось, что продукт гена, специфичного для данного гибрида, взаимодействовал с токсином гриба, что в результате приводило к развитию заболевания.
____

[quote, "Миф о трансгенной угрозе", Наука и жизнь]
____
С 30-х годов ХХ века для целей селекции человек использует радиацию и химикалии, вызывая мутагенез. К настоящему времени известно около 2200 сортов различных культур, полученных таким способом. Очевидно, что, в отличие от ГИР, такое грубое вмешательство затрагивает не один ген и имеет непредсказуемые последствия.
____

https://ru.wikipedia.org/wiki/%D0%90%D1%84%D1%80%D0%B8%D0%BA%D0%B0%D0%BD%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%B0%D1%8F_%D0%BF%D1%87%D0%B5%D0%BB%D0%B0[Пчёлы-убийцы] также получены без ручного вмешательства в ДНК, это обычные гибриды.

Отличный пример как древние селекционеры http://progenes.livejournal.com/22989.html[вывели кукурузу с повреждёнными генами питательности ] селекционируя её по размеру - исходная кукуруза была жирнее и витаминизированнее.

== Политика

=== Бесплодные сорта

Это похоже просто страшилка:
[quote, http://elementy.ru/lib/431731]
____
ГМ-растений со стерильными семенами на современном рынке нет.
____
Однако, есть то, что могло послужить основой этой страшилки
[quote, http://elementy.ru/lib/431512/431514]
____
В современном мире каждая семеноводческая фирма старается с производства сортов переходить на производство семян гибридов F1. Дело в том, что сорт можно длительно размножать без потери качества урожая. Фермер только один раз придет на фирму для покупки семян, а дальше в принципе может сам высевать семена собственного сбора*. Если же фирма предлагает более урожайные семена гибридов F1, то закупать их придется ежегодно. Ведь эффект гетерозиса в следующем поколении теряется.
Гибриды F1 позволяют фирмам-производителям семян сохранять свое know-how. Ведь нельзя воспроизвести «фирменный» гибрид F1, если нет родительских инбредных линий. Кроме того, фирмам-конкурентам трудно вовлекать гибриды F1 в свои программы скрещиваний с целью улучшить свои сорта за счет селекционных достижений конкурента. Таким образом, гибриды F1 очень выгодны фирмам-производителям.
____
Т.е. семена не стерильны, но урожайность и иные свойства уже не столь высоки. Стоит обратить внимание, что тут ничего не сказано о ГМО, речь о гибридах, который могут быть вовсе не ГМО.

=== Монополия иностранных производителей

Эта проблема подаётся немного некорректно - действительно производительность сельского хозяйства со всеми достижениями науки ощутимо выше, чем без них, а значит сельское хозяйство с ГМО в конкурентной борьбе одолеет сельское хозяйство без ГМО. Но раз ГМО, как мы выяснили, не опасно по своей сути (факт генетической модификации не делает организм ядовитым) и не несёт новых опасностей (также как и раньше нужно тестировать на безопасность), то что мешает приложить усилия и сделать рывок в биотехнологиях?

Если государство стремится к свободной торговле со всем миром, но не имеет своих биотехнологий, то для него вполне допустим временный запрет на фоне резкого увеличения инвестиций в сферу биотехнологий, взращивания компаний и специалистов могущих конкурировать с иностранными конкурентами и после этого можно открывать свой рынок для свободной конкуренции.

Однако важно понимать, что такой запрет нельзя вводить под предлогом опасности ГМО, если пропаганда убедит людей в том, что ГМО это яд, то отменить такой запрет будет предельно сложно. Такой временный запрет можно обосновывать только тем, что необходимо время для дополнительных исследований, и скорее всего запрет должен иметь заранее определённый срок.

Ну и государство оказавшееся в таком положении очевидно должно сделать вывод о необходимости развивать науку до того как отставание от других стран станет резко заметным.

=== Патентование

Это сложная тема, требующая отдельного обсуждения (подобная же проблема с лекарствами) - производитель вкладывает значительные ресурсы в разработку нового организма, но, когда он создан, скопировать его не так сложно, как разработать с нуля, поэтому может получиться так, что вкладывал один, а заработал другой, для защиты от этого производители патентуют свои изменения. Но защищая интересы производителей нужно не забыть об интересах общества. Вопрос как достичь баланса вне рамок дискуссии о ГМО.

=== Маркировка ГМО

Очевидно, что маркировка "Без ГМО" только поддерживает страхи людей. В составе продукта, вероятно, должно упоминаться как из составляющих продуктов ГМО, во всяком случае попадалась аргументация вида: "В ГМО продукте могут быть аллергены, несвойственные этому продукту, а аллергикам нужно знать, можно есть или нет.", хотя, мне кажется, аллергики не знают, что в каких ГМО есть, поэтому скорее всего для них должно быть отдельно написано, кому нельзя есть продукт.

== Заключение

*Генетическая модификация это инструмент*, как и все технологии, их можно использовать во благо, можно во вред, это зависит от человека, не нужно обвинять инструмент в человеческих недостатках (мы же не запрещаем кухонные ножи из-за того, что ими можно убить человека, нож в этом не виноват), и стоит учесть, что запреты точно мешают использовать технологию во благо, а вот те, кто хотят использовать во вред, всегда найдут способ обойти запрет.

ГМО могут быть опасны, также как и не ГМО, ради сверхприбыли многие готовы пожертвовать другими людьми, надо всё проверять, но некомпетентный человек не способен ничего проверить, поэтому приходится доверять науке. А если не доверять, то, вероятно, бояться уже поздно и ваш помидор следит за вами, а вы давно ГМО.

== Источники и дополнительная информация

. http://elementy.ru/lib/431731[ГМО: городские мифы, Елена Клещенко, «Химия и жизнь» №7, 2012]
. http://elementy.ru/lib/431804[Полет трансгенной пыльцы, Елена Клещенко, «Химия и жизнь» №9, 2012]
. http://elementy.ru/news?discuss=431862&return=1[Генетики выяснили, почему помидоры стали невкусными]
. http://www.nkj.ru/archive/articles/3642/[МИФ О ТРАНСГЕННОЙ УГРОЗЕ, НАУКА И ЖИЗНЬ, №11, 2003, Кандидат биологических наук В. Лебедев]
. http://www.popmech.ru/science/44879-geneticheskaya-modernizatsiya-razveivaem-mify-o-gmo/#full[Генетическая модернизация: развеиваем мифы о ГМО, Популярная механика, Август 2014, Александр Панчин, научный сотрудник сектора молекулярной эволюции Института проблем передачи информации РАН]
. http://elementy.ru/lib/431894[ГМО — мифические опасности, Александр Панчин]
http://elementy.ru/lib/431512[Растения-ГМО часть 1, Владимир Викторович Чуб, доктор биологических наук, профессор кафедры физиологии растений биологического факультета МГУ имени М. В. Ломоносова]
. http://elementy.ru/lib/431512/431513[Растения-ГМО часть 2, Владимир Викторович Чуб]
. http://elementy.ru/lib/431512/431514[Растения-ГМО часть 3, Владимир Викторович Чуб]
. http://expert.ru/expert/2014/13/fatalnyij-zapret/[Фатальный запрет, 24 мар 2014, Виталий Сараев]
. http://expert.ru/expert/2014/13/gmo-razdor/[ГМО-раздор, 24 мар 2014, Наталья Литвинова]
. http://postnauka.ru/themes/gmo[Серия статей и интервью на тему ГМО от проекта ПостНаука]
. http://www.computerra.ru/122541/gmo/[ГМО: деньги, рак и дутые сенсации]
. http://lenta.ru/articles/2013/08/14/gmomeme/[Ешь кукурузу, пока не уползла. Как мифы о ГМО укоренились в общественном мнении, 14 августа 2013, Николай Кондратьев]
. http://progenes.livejournal.com/tag/gmo[Блог специалиста по генетике растений и популяризатора науки Русланы Радчук]
. http://news.tut.by/it/333571.html[Козы-ГМО с лактоферрином в молоке]
. http://ria.ru/infografika/20130807/953861158.html[ГМО: что это такое и стоит ли бояться, Инфографика от РИАНовостей]
. http://geektimes.ru/post/246578/[Некоторые примеры ГМО в статье на GeekTimes]
. http://evoldar.com/evo21.htm[Генетические и онтогенетические основы эволюции. О переносе генов между мышами и мухами]
. http://elementy.ru/news/432487[Сотни генов человека всё еще могут заменить аналогичные гены дрожжей]
. http://en.wikipedia.org/wiki/List_of_most_valuable_crops_and_livestock_products[Ключевые продукты сельского хозяйства]
. http://lleo.me/dnevnik/2008/02/26.html[Хочу питаться генетически-модифицированными продуктами, 26 февраля 2008, Леонид Каганов, писатель]
. https://lurkmo.re/%D0%93%D0%9C%D0%9E[О ГМО на Lurkmore]
. http://bio-faq.ru/why/why059.html[Как алкоголь влияет на организм человека]
. http://www.ncbi.nlm.nih.gov/pubmed/117354[Mutagenic, cancerogenic and teratogenic effects of alcohol.]
