ГМО - генетически модифицированный организм, вкусный и полезный мутант
======================================================================

:toc:

== Определение

[quote, https://vk.com/just_wiki]
____
ГМО - генное оружие успешно использующееся для сокращения численности населения Земли с четырёх до семи миллиардов человек
____

https://ru.wikipedia.org/wiki/%D0%93%D0%B5%D0%BD%D0%B5%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8_%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D1%86%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BE%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%BC[ГМО]

== Мифы

Около половины опрошенных считает что гены есть только в ГМО

== Идеология

прогресс, еда будущего

== Цели модификации

Устойчивость к пестицидам

== Селекция

https://ru.wikipedia.org/wiki/%D1%E5%EB%E5%EA%F6%E8%FF[Селекция]

[quote, "Миф о трансгенной угрозе", Наука и жизнь]
____
Примером появления непредсказуемых эффектов в обычной селекции служит история с гибридом кукурузы "Техас". В начале 70-х огромные посевные площади этой культуры в США были опустошены грибковым заболеванием. Выяснилось, что продукт гена, специфичного для данного гибрида, взаимодействовал с токсином гриба, что в результате приводило к развитию заболевания.
____

[quote, "Миф о трансгенной угрозе", Наука и жизнь]
____
С 30-х годов ХХ века для целей селекции человек использует радиацию и химикалии, вызывая мутагенез. К настоящему времени известно около 2200 сортов различных культур, полученных таким способом. Очевидно, что в отличие от ГИР такое грубое вмешательство затрагивает не один ген и имеет непредсказуемые последствия.
____

Пчёлы-убийцы


== Политика

Бесплодные сорта
Монополия иностранных производителей (по причине их технологического превосходства)
Патентование
Маркировка ГМО

== Источники и дополнительная информация
. http://www.nkj.ru/archive/articles/3642/[МИФ О ТРАНСГЕННОЙ УГРОЗЕ, НАУКА И ЖИЗНЬ, №11, 2003, Кандидат биологических наук В. Лебедев]
. http://www.popmech.ru/science/44879-geneticheskaya-modernizatsiya-razveivaem-mify-o-gmo/#full[Генетическая модернизация: развеиваем мифы о ГМО, Популярная механика, Август 2014, Александр Панчин, научный сотрудник сектора молекулярной эволюции Института проблем передачи информации РАН]
. http://expert.ru/expert/2014/13/fatalnyij-zapret/[Фатальный запрет, 24 мар 2014, Виталий Сараев]
. http://expert.ru/expert/2014/13/gmo-razdor/[ГМО-раздор, 24 мар 2014, Наталья Литвинова]
. http://postnauka.ru/themes/gmo[Серия статей и интервью на тему ГМО от проекта ПостНаука]
. http://lenta.ru/articles/2013/08/14/gmomeme/[Ешь кукурузу, пока не уползла. Как мифы о ГМО укоренились в общественном мнении, 14 августа 2013, Николай Кондратьев]
. http://news.tut.by/it/333571.html[Козы-ГМО с лактоферрином в молоке]
. http://ria.ru/infografika/20130807/953861158.html[ГМО: что это такое и стоит ли бояться, Инфографика от РИАНовостей]
. http://geektimes.ru/post/246578/[Некоторые примеры ГМО в статье на GeekTimes]
. http://lleo.me/dnevnik/2008/02/26.html[Хочу питаться генетически-модифицированными продуктами, 26 февраля 2008, Леонид Каганов, писатель]
. https://lurkmo.re/%D0%93%D0%9C%D0%9E[О ГМО на Lurkmore]
. http://bio-faq.ru/why/why059.html[Как алкоголь влияет на организм человека]
. http://www.ncbi.nlm.nih.gov/pubmed/117354[Mutagenic, cancerogenic and teratogenic effects of alcohol.]
