== Определения

[quote, https://vk.com/just_wiki]
____
ГМО - генное оружие успешно использующееся для сокращения численности населения Земли с четырёх до семи миллиардов человек
____

ГМО - https://ru.wikipedia.org/wiki/%D0%93%D0%B5%D0%BD%D0%B5%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8_%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D1%86%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BE%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%BC[генетически модифицированный организм], для того чтобы было понятно что это за монстр, нужно уточнить кто такие гены. В минимальном виде цепочка выглядит так:
https://ru.wikipedia.org/wiki/%D0%9E%D1%80%D0%B3%D0%B0%D0%BD%D0%B8%D0%B7%D0%BC[Организмы] состоят из
https://ru.wikipedia.org/wiki/%D0%9A%D0%BB%D0%B5%D1%82%D0%BA%D0%B0[клеток], в клетках есть
https://ru.wikipedia.org/wiki/%D0%9A%D0%BB%D0%B5%D1%82%D0%BE%D1%87%D0%BD%D0%BE%D0%B5_%D1%8F%D0%B4%D1%80%D0%BE[ядро], в ядре есть
https://ru.wikipedia.org/wiki/%D0%A5%D1%80%D0%BE%D0%BC%D0%BE%D1%81%D0%BE%D0%BC%D0%B0[хромосомы], в каждой хромосоме упакована молекула
https://ru.wikipedia.org/wiki/%D0%94%D0%B5%D0%B7%D0%BE%D0%BA%D1%81%D0%B8%D1%80%D0%B8%D0%B1%D0%BE%D0%BD%D1%83%D0%BA%D0%BB%D0%B5%D0%B8%D0%BD%D0%BE%D0%B2%D0%B0%D1%8F_%D0%BA%D0%B8%D1%81%D0%BB%D0%BE%D1%82%D0%B0[ДНК], ДНК это длинная молекула состоящая из
https://ru.wikipedia.org/wiki/%D0%9D%D1%83%D0%BA%D0%BB%D0%B5%D0%BE%D1%82%D0%B8%D0%B4%D1%8B[нуклеотидов], участок ДНК состоящий из нескольких нуклеотидов и выполняющий законченную функцию (влияющий одну или несколько характеристик организма) и называется https://ru.wikipedia.org/wiki/%D0%93%D0%B5%D0%BD[геном]. Набор ДНК из всех хромосом клетки и есть основное хранилище наследственной информации.
Чаще всего при генетической модификации изменение касается одного гена отвечающего за необходимый функционал, во многих случаях ген (https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B0%D0%BD%D1%81%D0%B3%D0%B5%D0%BD[трансген]) с необходимыми функциями берётся аналогичный тому организму который обладает желаемой характеристикой.

== Концепция

Эволюция не делает совершенства, он делает рабочие решения. Например, http://geektimes.ru/post/248678/[зелёные растения умеют поглощать далеко не весь спектр солнечного излучения] и возможно мы когда-то сможем доработать растения повысив их эффективность - они будут расти быстрее при той же освещённости.
Также и с едой для человека - в природе нет такого продукта который содержал бы всё необходимое для питания человека, эволюции такой продукт не требовался т.к. наши всеядные предки до освоения земледелия и скотоводства вынуждены были питаться разнообразными продуктами (что нашёл, то и съел).
С практической точки зрения было бы значительно удобнее выращивать и употреблять небольшое количество культур. но получать из них все необходимые человеку вещества. В пределе может даже один фрукт со всем необходимым - некое питательное яблоко, хотя завязываться на одну культуру рискованно, лучше иметь множество взаимозаменяемых.
Конечно любители высокой кухни могут не обрадоваться такому варианту, но для них останутся и старые продукты, а значительная часть людей предпочтёт тратить на еду и её приготовление меньше времени и денег, получая при этом максимально полезную пищу без сложных диет.

Таким образом примитивная генетическая модификация, которую делают сегодня, это лишь первые шаги в большом пути по обеспечению человечества качественным и удобным питанием.

И вполне возможно что дерево на котором будет расти такой универсальный питательный фрукт будет нашим домом - оно будет вырастать с комнатами пригодными для проживания человека - живой, саморемонтирующийся дом.

=== Текущие цели модификации

Текущие цели генной модификации часто далеки от вышеописанной концепции, хотя есть и примеры идущие правильным путём (например рис богатый витамином А):

. устойчивость к пестицидам - заливают пестицидами, гибнет всё кроме нужного растения, не самый позитивный вариант, но при таком подходе в конечном продукте пестицидов должно быть меньше т.к. заливают на ранней стадии. Не ГМО тоже заливают пестицидами, но чаще и больше.
. устойчивость к загрязнителям почвы - для выращивание например на засоленных почвах где почти ничего не растёт.
. устойчивость к вредителям - что может быть радостнее чем картошка без колорадского жука?
. повышение урожайности - плоды крупнее и число их больше.
. устойчивость к колебаниям погоды, морозостойкость.
. получение каких-либо сложнополучаемых веществ, в основном лекарственных, например инсулина.
. повышение полезности - пока редко, но настанет и для этого время.
. наделение организмов дополнительными функциями, например, научить бактерии перерабатывать отходы или не допускать развития кариеса.

== Страшилки и мифы

К сожалению множество людей позволяют себе рассуждать о том, о чем не имеют ни малейшего понятий, например согласно опросам около половины опрошенных считает что гены есть только в ГМО, а значит они не освоили даже школьный курс биологии.
Необразованным людям свойственно бояться прогресса т.к. для них он выглядит непонятным как колдовство, когда-то боялись что от шума паровозов коровы перестанут доиться, некоторые даже агрессивны - были случаи нападений на лаборатории.
Всё непонятное или ненравящееся необразованные люди любят запрещать, хотя запреты редко приводят к положительным результатам и редко сторонники запретов бывают последовательными - автомобили очевидно очень опасны, хотя что-то никто не спешит их запрещать.

=== Превращение потомков людей в мутантов

*Генетическая модификация по своему результату принципиально (качественно) не отличается от https://ru.wikipedia.org/wiki/%D1%E5%EB%E5%EA%F6%E8%FF[селекции]*, только при селекции селекционер долго ждет появления нужной ему https://ru.wikipedia.org/wiki/%D0%9C%D1%83%D1%82%D0%B0%D1%86%D0%B8%D1%8F[мутации], а генетический инженер сам вносит нужное изменение в ДНК. Поэтому опасность ГМО не отличается от опасности новых сортов полученных старыми мичуринскими методами, точнее она даже ниже т.к. даже случайные мутации могут затрагивать множество генов помимо желаемого, а значит *при селекции непредсказуемость последствий выше чем при целенаправленном изменении конкретного гена*.
А раз принципиальной разницы нет, то и нет никакого магического действия - мы едим помидоры и селёдку, однако это не делает наших потомков похожими на кого-то из съеденных (потому что https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%BF%D0%B0%D1%80%D0%B0%D1%86%D0%B8%D1%8F_%D0%94%D0%9D%D0%9A[ДНК защищена от поломок] но в данном случае даже этого не требуется т.к. в нашем желудке под действием серной кислоты и ферментов все белки разлагаются на аминокислоты), поедание помидора с геном селедки не отличается от поедания этих двоих, точнее может оличатся - любой новый сорт (выведенный селекционерами или созданный генными инженерами) может содержать токсины или быть опасен чем-то ещё, и конечно его необходимо всячески проверять, на удивление ГМО проверяют строже чем обычные гибриды, полученные например радиоактивным облучением семян.
Ещё важный момент - всё живое на Земле родственно, никакой проблемы в переносе генов нет, например: "Ученые перенесли ген, контролирующий развитие глаза у мыши в геном дрозофилы. ... мышиный ген индуцировал у мухи развитие мушиных глаз." Т.е. *мы настолько близки что даже гены мухи и мыши взаимозаменяемы*.

=== Они же не проверены временем

На самом деле есть исследования на многих поколениях подопытных животных, за десятки лет исследований было всего несколько негативных результатов которые не подтвердились при более тщательной проверке.

Зато алкоголь проверен - он тщательно исследован и точно известно что он является https://ru.wikipedia.org/wiki/%D0%9C%D1%83%D1%82%D0%B0%D0%B3%D0%B5%D0%BD%D1%8B[мутагеным] фактором т.е. может сделать потомков уродами, но что-то ГМО боятся больше чем водки.

Ну и на самом деле *не ГМО продуктов нет*, все значимые культуры были селекционированы человеком ещё на заре сельского хозяйства и они значительно отличаются от своих диких собратьев не только размерами, но и другими свойствами т.е. они генетически отличаются от своих предков, например зерновые это мутанты которые в отличии от диких предков прорастают и дают урожай в первый год (в дикой природе многие семена прорастают через год и более для страховки от непогоды), а также не выбрасывают зёрна из колосьев чтобы человек мог их собрать. Размеры таже отличаются значительно, початок дикой кукурузы во много раз меньше культурной. Мало того, некоторые дикие предки культурных растений ядовиты - например у https://ru.wikipedia.org/wiki/%D0%9C%D0%B8%D0%BD%D0%B4%D0%B0%D0%BB%D1%8C[миндаля]. А что сделали селекционеры с помощью радиации и токсинов задолго до ГМО и не представить, т.е. мы *ели, едим и будем есть ГМО, без них человечество не прокормить*.

=== Аллергенность

Также не зависит от способа получения, основные аллергены существовали ещё до изобретения ГМО, поэтому любой новый продукт надо тестировать на содержание известный и не известных аллергенов.

=== Передача генов устойчивости к пестицидам диким растениям

Это возможно, хотя согласно исследованиям маловероятно, конечно надо следить, однако, например бактерии и без ГМО быстро приспосабливаются к антибиотикам (http://www.popmech.ru/science/15919-ustoychivost-patogenov-k-antibiotikam-stanovitsya-globalnoy-problemoy/[тыц], http://www.popmech.ru/science/56345-antibiotikovyy-apokalipsis/#full[тыц]), но антибиотики никто не предлагает запретить. Также и растения без всяких ГМО постепенно эволюционируют в сторону устойчивости к пестицидам, запрет ГМО этого не изменит.

=== Раз жуки не едят и нам нельзя

Тут ГМО тоже не отличается от сортов полученных селекцией - селекционер выбирает растения не интересующие паразитов по тем или иным причинам, в том числе они могут быть ядовиты для паразитов, но это не значит что и для человека они ядовиты - "что человеку хорошо, то жуку смерть", например есть белок-токсин, нарушающий пищеварение у насекомых, но не у теплокровных животных.
Безопасность для человека определяется исследования на животных максимально близких к человеку, а потом и на человеке, жуки тут не авторитеты.

== Селекция

Несколько примеров того как без ГМО можно натворить дел, надо быть осторожными, но не запрещать, а контролировать.

[quote, "Миф о трансгенной угрозе", Наука и жизнь]
____
Примером появления непредсказуемых эффектов в обычной селекции служит история с гибридом кукурузы "Техас". В начале 70-х огромные посевные площади этой культуры в США были опустошены грибковым заболеванием. Выяснилось, что продукт гена, специфичного для данного гибрида, взаимодействовал с токсином гриба, что в результате приводило к развитию заболевания.
____

[quote, "Миф о трансгенной угрозе", Наука и жизнь]
____
С 30-х годов ХХ века для целей селекции человек использует радиацию и химикалии, вызывая мутагенез. К настоящему времени известно около 2200 сортов различных культур, полученных таким способом. Очевидно, что в отличие от ГИР такое грубое вмешательство затрагивает не один ген и имеет непредсказуемые последствия.
____

https://ru.wikipedia.org/wiki/%D0%90%D1%84%D1%80%D0%B8%D0%BA%D0%B0%D0%BD%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%B0%D1%8F_%D0%BF%D1%87%D0%B5%D0%BB%D0%B0[Пчёлы-убийцы] также получены без ручного вмешательства в ДНК, это обычные гибриды.

== Политика

Бесплодные сорта

Монополия иностранных производителей (по причине их технологического превосходства)

Патентование

Маркировка ГМО

== Заключение

*Генетическая модификация это инструмент*, как и вся наука, её можно использовать во благо, можно во вред, это зависит от человека, не нужно обвинять технологию/инструмент в человеческих недостатках (мы же не запрещаем кухонные ножи из-за того что ими можно убить человека, нож в этом не виноват) и стоит учесть, что запреты точно мешают использовать технологию во благо, а вот те, кто хотят использовать во вред, всегда найдут способ обойти запрет.

== Источники и дополнительная информация

. http://elementy.ru/lib/431731[ГМО: городские мифы, Елена Клещенко, «Химия и жизнь» №7, 2012]
. http://elementy.ru/lib/431804[Полет трансгенной пыльцы, Елена Клещенко, «Химия и жизнь» №9, 2012]
. http://elementy.ru/news?discuss=431862&return=1[Генетики выяснили, почему помидоры стали невкусными]
. http://www.nkj.ru/archive/articles/3642/[МИФ О ТРАНСГЕННОЙ УГРОЗЕ, НАУКА И ЖИЗНЬ, №11, 2003, Кандидат биологических наук В. Лебедев]
. http://www.popmech.ru/science/44879-geneticheskaya-modernizatsiya-razveivaem-mify-o-gmo/#full[Генетическая модернизация: развеиваем мифы о ГМО, Популярная механика, Август 2014, Александр Панчин, научный сотрудник сектора молекулярной эволюции Института проблем передачи информации РАН]
. http://elementy.ru/lib/431894[ГМО — мифические опасности, Александр Панчин]
http://elementy.ru/lib/431512[Растения-ГМО часть 1, Владимир Викторович Чуб, доктор биологических наук, профессор кафедры физиологии растений биологического факультета МГУ имени М. В. Ломоносова]
. http://elementy.ru/lib/431512/431513[Растения-ГМО часть 2, Владимир Викторович Чуб]
. http://elementy.ru/lib/431512/431514[Растения-ГМО часть 3, Владимир Викторович Чуб]
. http://expert.ru/expert/2014/13/fatalnyij-zapret/[Фатальный запрет, 24 мар 2014, Виталий Сараев]
. http://expert.ru/expert/2014/13/gmo-razdor/[ГМО-раздор, 24 мар 2014, Наталья Литвинова]
. http://postnauka.ru/themes/gmo[Серия статей и интервью на тему ГМО от проекта ПостНаука]
. http://www.computerra.ru/122541/gmo/[ГМО: деньги, рак и дутые сенсации]
. http://lenta.ru/articles/2013/08/14/gmomeme/[Ешь кукурузу, пока не уползла. Как мифы о ГМО укоренились в общественном мнении, 14 августа 2013, Николай Кондратьев]
. http://progenes.livejournal.com/tag/gmo[Блог специалиста по генетике растений и популяризатора науки Русланы Радчук]
. http://news.tut.by/it/333571.html[Козы-ГМО с лактоферрином в молоке]
. http://ria.ru/infografika/20130807/953861158.html[ГМО: что это такое и стоит ли бояться, Инфографика от РИАНовостей]
. http://geektimes.ru/post/246578/[Некоторые примеры ГМО в статье на GeekTimes]
. http://evoldar.com/evo21.htm[Генетические и онтогенетические основы эволюции. О переносе генов между мышыми и мухами]
. http://en.wikipedia.org/wiki/List_of_most_valuable_crops_and_livestock_products[Ключевые продукты сельского хозяйства]
. http://lleo.me/dnevnik/2008/02/26.html[Хочу питаться генетически-модифицированными продуктами, 26 февраля 2008, Леонид Каганов, писатель]
. https://lurkmo.re/%D0%93%D0%9C%D0%9E[О ГМО на Lurkmore]
. http://bio-faq.ru/why/why059.html[Как алкоголь влияет на организм человека]
. http://www.ncbi.nlm.nih.gov/pubmed/117354[Mutagenic, cancerogenic and teratogenic effects of alcohol.]
